# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model1 import Model1  # noqa: E501
from swagger_client.rest import ApiException


class TestModel1(unittest.TestCase):
    """Model1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel1(self):
        """Test Model1"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model1.Model1()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
