# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model9 import Model9  # noqa: E501
from swagger_client.rest import ApiException


class TestModel9(unittest.TestCase):
    """Model9 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel9(self):
        """Test Model9"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model9.Model9()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
