# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parser_api import ParserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParserApi(unittest.TestCase):
    """ParserApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.parser_api.ParserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_parser_v1_rule_idrule(self):
        """Test case for post_parser_v1_rule_idrule

        """
        pass


if __name__ == '__main__':
    unittest.main()
