# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.schema_api import SchemaApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSchemaApi(unittest.TestCase):
    """SchemaApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.schema_api.SchemaApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_schema_v1_info_id(self):
        """Test case for get_schema_v1_info_id

        """
        pass

    def test_post_schema_v1_group_type(self):
        """Test case for post_schema_v1_group_type

        """
        pass

    def test_post_schema_v1_query_skip_limit(self):
        """Test case for post_schema_v1_query_skip_limit

        """
        pass


if __name__ == '__main__':
    unittest.main()
