# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.domain_api import DomainApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDomainApi(unittest.TestCase):
    """DomainApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.domain_api.DomainApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_domain_v1_id(self):
        """Test case for delete_domain_v1_id

        """
        pass

    def test_get_domain_v1_info_id(self):
        """Test case for get_domain_v1_info_id

        """
        pass

    def test_patch_domain_v1_update_id_field_value(self):
        """Test case for patch_domain_v1_update_id_field_value

        """
        pass

    def test_post_domain_v1_add(self):
        """Test case for post_domain_v1_add

        """
        pass

    def test_post_domain_v1_query_skip_limit(self):
        """Test case for post_domain_v1_query_skip_limit

        """
        pass

    def test_put_domain_v1_update_id(self):
        """Test case for put_domain_v1_update_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
