# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.sentence_api import SentenceApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSentenceApi(unittest.TestCase):
    """SentenceApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.sentence_api.SentenceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_sentence_v1_idrule_id(self):
        """Test case for delete_sentence_v1_idrule_id

        """
        pass

    def test_get_sentence_v1_info_idrule_id(self):
        """Test case for get_sentence_v1_info_idrule_id

        """
        pass

    def test_post_sentence_v1_add_idrule(self):
        """Test case for post_sentence_v1_add_idrule

        """
        pass

    def test_put_sentence_v1_update_idrule_id(self):
        """Test case for put_sentence_v1_update_idrule_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
