# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.execute_api import ExecuteApi  # noqa: E501
from swagger_client.rest import ApiException


class TestExecuteApi(unittest.TestCase):
    """ExecuteApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.execute_api.ExecuteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_post_execute_v1_local_domain_key(self):
        """Test case for post_execute_v1_local_domain_key

        """
        pass

    def test_post_execute_v1_rule_idrule(self):
        """Test case for post_execute_v1_rule_idrule

        """
        pass

    def test_post_execute_v1_rule_idrule_example_idexample(self):
        """Test case for post_execute_v1_rule_idrule_example_idexample

        """
        pass


if __name__ == '__main__':
    unittest.main()
