# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model5 import Model5  # noqa: E501
from swagger_client.rest import ApiException


class TestModel5(unittest.TestCase):
    """Model5 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel5(self):
        """Test Model5"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model5.Model5()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
