# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model12 import Model12  # noqa: E501
from swagger_client.rest import ApiException


class TestModel12(unittest.TestCase):
    """Model12 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel12(self):
        """Test Model12"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model12.Model12()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
