# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.rule_api import RuleApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRuleApi(unittest.TestCase):
    """RuleApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.rule_api.RuleApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_delete_rule_v1_id(self):
        """Test case for delete_rule_v1_id

        """
        pass

    def test_get_rule_v1_info_id(self):
        """Test case for get_rule_v1_info_id

        """
        pass

    def test_patch_rule_v1_update_id_field_value(self):
        """Test case for patch_rule_v1_update_id_field_value

        """
        pass

    def test_post_rule_v1_add_iddomain(self):
        """Test case for post_rule_v1_add_iddomain

        """
        pass

    def test_post_rule_v1_query_iddomain_skip_limit(self):
        """Test case for post_rule_v1_query_iddomain_skip_limit

        """
        pass

    def test_put_rule_v1_update_iddomain_id(self):
        """Test case for put_rule_v1_update_iddomain_id

        """
        pass


if __name__ == '__main__':
    unittest.main()
