# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.model15 import Model15  # noqa: E501
from swagger_client.rest import ApiException


class TestModel15(unittest.TestCase):
    """Model15 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testModel15(self):
        """Test Model15"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.model15.Model15()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
