# coding: utf-8

# flake8: noqa
"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from swagger_client.models.json import Json
from swagger_client.models.model1 import Model1
from swagger_client.models.model10 import Model10
from swagger_client.models.model11 import Model11
from swagger_client.models.model12 import Model12
from swagger_client.models.model13 import Model13
from swagger_client.models.model14 import Model14
from swagger_client.models.model15 import Model15
from swagger_client.models.model2 import Model2
from swagger_client.models.model3 import Model3
from swagger_client.models.model4 import Model4
from swagger_client.models.model5 import Model5
from swagger_client.models.model6 import Model6
from swagger_client.models.model7 import Model7
from swagger_client.models.model8 import Model8
from swagger_client.models.model9 import Model9
from swagger_client.models.order import Order
