# coding: utf-8

"""
    Fabulator API

    Endpoint Fabulator project  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: torloneg@gmail.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.models.model10 import Model10  # noqa: F401,E501


class Model11(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'select': 'str',
        'order': 'Model10',
        'query': 'str'
    }

    attribute_map = {
        'select': 'select',
        'order': 'order',
        'query': 'query'
    }

    def __init__(self, select='{}', order=None, query='{}'):  # noqa: E501
        """Model11 - a model defined in Swagger"""  # noqa: E501

        self._select = None
        self._order = None
        self._query = None
        self.discriminator = None

        self.select = select
        if order is not None:
            self.order = order
        self.query = query

    @property
    def select(self):
        """Gets the select of this Model11.  # noqa: E501


        :return: The select of this Model11.  # noqa: E501
        :rtype: str
        """
        return self._select

    @select.setter
    def select(self, select):
        """Sets the select of this Model11.


        :param select: The select of this Model11.  # noqa: E501
        :type: str
        """
        if select is None:
            raise ValueError("Invalid value for `select`, must not be `None`")  # noqa: E501

        self._select = select

    @property
    def order(self):
        """Gets the order of this Model11.  # noqa: E501


        :return: The order of this Model11.  # noqa: E501
        :rtype: Model10
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this Model11.


        :param order: The order of this Model11.  # noqa: E501
        :type: Model10
        """

        self._order = order

    @property
    def query(self):
        """Gets the query of this Model11.  # noqa: E501


        :return: The query of this Model11.  # noqa: E501
        :rtype: str
        """
        return self._query

    @query.setter
    def query(self, query):
        """Sets the query of this Model11.


        :param query: The query of this Model11.  # noqa: E501
        :type: str
        """
        if query is None:
            raise ValueError("Invalid value for `query`, must not be `None`")  # noqa: E501

        self._query = query

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Model11, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Model11):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
